#!/usr/bin/lua

local pretty_hostname = require 'pretty_hostname'
local sysconfig = require 'graviton.sysconfig'

-- Initial
if not sysconfig.graviton_version then
  local site = require 'graviton.site_config'
  local util = require 'graviton.util'
  local uci = require('luci.model.uci').cursor()

  local system = uci:get_first('system', 'system')

  pretty_hostname.set(uci, (site.hostname_prefix or '') .. util.node_id())
  uci:set('system', system, 'timezone', site.timezone)

  uci:save('system')
end
