#!/usr/bin/lua

local sysconfig = require 'graviton.sysconfig'

local fs = require 'nixio.fs'
local util = require 'luci.util'


-- Save the Graviton version in the sysconfig so we know which version we
-- upgraded from after the next upgrade
sysconfig.graviton_version = util.trim(fs.readfile('/lib/graviton/graviton-version'))
