#!/bin/sh


wait=3


wait_failsafe_mode() {
	sleep $wait
	uci set 'graviton-failsafe-mode.@failsafe_mode[0].enabled=1'
	uci commit graviton-failsafe-mode
	reboot
}


if [ "$BUTTON" = wps -o "$BUTTON" = reset ]; then
	case "$ACTION" in
		pressed)
			wait_failsafe_mode &
			PID=$!
			echo $PID > /tmp/.wait_failsafe_mode
			;;
		released)
			if [ -r /tmp/.wait_failsafe_mode ]; then
				kill $(cat /tmp/.wait_failsafe_mode)
				rm /tmp/.wait_failsafe_mode
			fi
			;;
	esac
fi
