#!/bin/sh /etc/rc.common

START=50

USE_PROCD=1
PROG=/usr/sbin/telnetd

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" -F -l /lib/graviton/setup-mode/ash-login
	procd_close_instance
}
