#!/usr/bin/lua

local sysconfig = require 'graviton.sysconfig'

local lutil = require 'luci.util'
local uci = require('luci.model.uci').cursor()


uci:section('network', 'interface', 'graviton',
  {
    type = 'bridge',
  }
)

local ifname = uci:get('network', 'graviton', 'ifname')

if type(ifname) == 'string' then
  uci:delete('network', 'graviton', 'ifname')
  for x in ifname:gmatch("[^%s]+") do
    uci:add_to_set('network', 'graviton', 'ifname', x)
  end
end
-- *********
--    CHANGE
--**********
if sysconfig.lan_ifname and not ifname and not uci:get_bool('network', 'mesh_lan', 'auto') then
  for _, lanif in ipairs(lutil.split(sysconfig.lan_ifname, ' ')) do
    uci:add_to_set('network', 'graviton', 'ifname', lanif)
  end
end


uci:set('network', 'graviton', 'macaddr', sysconfig.primary_mac)

uci:save('network')
