#!/usr/bin/lua

local site = require 'graviton.site_config'
local util = require 'graviton.util'

local uci = require('luci.model.uci').cursor()


local function is_disabled(config, name)
  local disabled = config and config.disabled
  if uci:get('wireless', name) then
    disabled = uci:get_bool('wireless', name, 'disabled')
  end

  return disabled and 1 or 0
end

local function configure_wifiif(config, radio, index, suffix)
  local name = 'graviton_' .. radio
  local disabled = is_disabled(config, name)

  uci:delete('wireless', name)

  if not config then
    return
  end

  local macaddr = util.get_wlan_mac(radio, index, 1)
  if not macaddr then
    return
  end

  uci:section('wireless', 'wifi-iface', name,
    {
      device = radio,
      network = 'graviton',
      mode = 'ap',
      ssid = config.ssid,
      macaddr = macaddr,
      ifname = suffix and 'graviton' .. suffix,
      disabled = disabled,
    }
  )
end

local function configure_radio(radio, index, config)
  local suffix = radio:match('^radio(%d+)$')

  configure_wifiif(config.ap, radio, index, suffix)
end

util.iterate_radios(configure_radio)

uci:save('wireless')
